apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haproxy-k8s-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy-k8s-sync.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  haproxy_dataplane_username: {{ .Values.env.haproxy.username | quote }}
  haproxy_dataplane_password: {{ .Values.env.haproxy.password | quote }}
  haproxy_dataplane_token: {{ .Values.env.haproxy.token | quote }}
