apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-k8s-sync-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: haproxy-k8s-sync-controller
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haproxy-k8s-sync-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: haproxy-k8s-sync-controller
subjects:
  - kind: ServiceAccount
    name: haproxy-k8s-sync-controller
